version: "3.9"
services:
  app-service:
    image: skibur/app-service
    restart: "always" 
    environment: 
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP}
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    image: skibur/auth-service
    restart: "always" 
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
      POSTMARK_AUTH_TOKEN: ${POSTMARK_AUTH_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
      
volumes:
  db:
    driver: local
