[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "^0"
reqwest = { version = "^0", features = ["json"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tokio = { version = "^1", features = ["full"] }
tower-http = { version = "^0", features = ["fs"] }
uuid = { version = "^1", features = ["v4", "serde"] }
openssl = { version = "^0", features = ["vendored"] }
