[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
reqwest = { version = "^0", features = ["json"] }

[dependencies]
axum = "^0"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1.0"
tokio = { version = "^1", features = ["full"] }
tower-http = { version = "^0", features = ["fs"] }
uuid = { version = "^1", features = ["v4", "serde"] }
# needed to run on docker properly
openssl = { version = "^0", features = ["vendored"] }
async-trait = "0.1.83"
regex = "1.11.0"
tonic = "0.12.3"
jsonwebtoken = "9.3.0"
prost = "^0.13"
bacon = "3.1.1"

[build-dependencies]
tonic-build = "^0.12"
